# Generated by Django 4.0.1 on 2023-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_admin_bass_new_review_video_guitarimage_bassimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(max_length=111111111111, unique=True),
        ),
    ]
