# Generated by Django 4.0.1 on 2023-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_admin_username_alter_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='default_strings',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='scale',
            field=models.CharField(max_length=200),
        ),
    ]
