# Generated by Django 4.0.1 on 2023-06-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_guitar_default_strings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
                ('date_order', models.DateTimeField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bassimage',
            name='item_name',
        ),
        migrations.AddField(
            model_name='guitar',
            name='type',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='item_bought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.guitar'),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Bass',
        ),
        migrations.DeleteModel(
            name='BassImage',
        ),
        migrations.AddField(
            model_name='order',
            name='item_bought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.guitar'),
        ),
    ]
