# Generated by Django 4.2.2 on 2023-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_name_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
